steps:

### Deployment by adapt
  - id: 'pre-deploy'
    name: 'gcr.io/cloud-builders/gcloud'
    env:
    entrypoint: 'bash'
    args:
      - '-c'
      - | 
          npm install -g @adpt/cli
          gcloud container clusters get-credentials autopilot-cluster \
            --region=europe-west1 \
            --project devops2-analiza
          gcloud auth configure-docker --quiet
          cd deploy/  
          export KUBE_DOCKER_REPO=gcr.io/devops2-analiza/movieapp

# Run Adapt
  - id: 'deploy'
    name: 'gcr.io/devops2-analiza/movieapp'
    entrypoint: 'adapt' 
    env: 
    - 'KUBECONFIG=gcr.io/devops2-analiza/movieapp'
    - 'KUBE_DOCKER_REPO=gcr.io/devops2-analiza/movieapp'
    # args: ['run','k8s-test','--deployID','prod-movieapp']
    args: ['update','prod-movieapp']
    dir: 'deploy'
             

### Timeout
timeout: "1600s"
options:
 logging: CLOUD_LOGGING_ONLY
